
project_id = "pktikklryhhemfidupor"

[functions.migrate-temp-user]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
