// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pktikklryhhemfidupor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrdGlra2xyeWhoZW1maWR1cG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTU0OTQsImV4cCI6MjA2MTA5MTQ5NH0.D-CokcD9tpv17TeTNxmiWPFvJQUsTDRwYB_WvOM_rsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);